# Generated by Django 4.1.6 on 2023-02-07 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "add_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="address",
            name="zip",
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
